spring:
  application:
    name: web-shop-api
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    mongodb:
      host: localhost
      port: 27017
      database: web-shop

server:
  servlet:
    session:
      timeout: 30m # Session timeout duration

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.8
